package cleaner

import (
	"unicode"

	"golang.org/x/text/runes"
)

var (
	Diacritic      = runes.Remove(runes.In(unicode.Mn))
	LatinDiacritic = runes.Remove(latinDiacritic)
)

var latinDiacritic = runes.Predicate(func(r rune) bool {
	switch {
	case r >= '\u0300' && r <= '\u036F', // COMBINING GRAVE ACCENT..COMBINING LATIN SMALL LETTER X
		r >= '\u1AB0' && r <= '\u1ABD',         // COMBINING DOUBLED CIRCUMFLEX ACCENT..COMBINING PARENTHESES BELOW
		r >= '\u1ABF' && r <= '\u1ACE',         // COMBINING LATIN SMALL LETTER W BELOW..COMBINING LATIN SMALL LETTER INSULAR T
		r >= '\u1DC0' && r <= '\u1DFF',         // COMBINING DOTTED GRAVE ACCENT..COMBINING RIGHT ARROWHEAD AND DOWN ARROWHEAD BELOW
		r >= '\u20D0' && r <= '\u20DC',         // COMBINING LEFT HARPOON ABOVE..COMBINING FOUR DOTS ABOVE
		r == '\u20E1',                          // COMBINING LEFT RIGHT ARROW ABOVE
		r >= '\u20E5' && r <= '\u20F0',         // COMBINING REVERSE SOLIDUS OVERLAY..COMBINING ASTERISK ABOVE
		r >= '\u302A' && r <= '\u302D',         // IDEOGRAPHIC LEVEL TONE MARK..IDEOGRAPHIC ENTERING TONE MARK
		r >= '\uFE00' && r <= '\uFE0F',         // VARIATION SELECTOR-1..VARIATION SELECTOR-16
		r >= '\uFE20' && r <= '\uFE2D',         // COMBINING LIGATURE LEFT HALF..COMBINING CONJOINING MACRON BELOW
		r == '\U000101FD',                      // PHAISTOS DISC SIGN COMBINING OBLIQUE STROKE
		r == '\U0001133B',                      // COMBINING BINDU BELOW
		r >= '\U0001CF00' && r <= '\U0001CF2D', // ZNAMENNY COMBINING MARK GORAZDO NIZKO S KRYZHEM ON LEFT..ZNAMENNY COMBINING MARK KRYZH ON LEFT
		r >= '\U0001CF30' && r <= '\U0001CF46', // ZNAMENNY COMBINING TONAL RANGE MARK MRACHNO..ZNAMENNY PRIZNAK MODIFIER ROG
		r >= '\U0001D167' && r <= '\U0001D169', // MUSICAL SYMBOL COMBINING TREMOLO-1..MUSICAL SYMBOL COMBINING TREMOLO-3
		r >= '\U0001D17B' && r <= '\U0001D182', // MUSICAL SYMBOL COMBINING ACCENT..MUSICAL SYMBOL COMBINING LOURE
		r >= '\U0001D185' && r <= '\U0001D18B', // MUSICAL SYMBOL COMBINING DOIT..MUSICAL SYMBOL COMBINING TRIPLE TONGUE
		r >= '\U0001D1AA' && r <= '\U0001D1AD', // MUSICAL SYMBOL COMBINING DOWN BOW..MUSICAL SYMBOL COMBINING SNAP PIZZICATO
		r >= '\U000E0100' && r <= '\U000E01EF': // VARIATION SELECTOR-17..VARIATION SELECTOR-256
		return true
	default:
		return false
	}
})
